"""Contract tests for tictactoe.game. These define "done" for the rules engine.

Do not edit this file to make it pass. Change tictactoe/game.py instead.
"""

import pytest

from tictactoe.game import Game, InvalidMove


def play(game, moves):
    for row, col in moves:
        game.place(row, col)


def test_new_game_is_empty_and_x_moves_first():
    game = Game()
    assert game.board == ((None, None, None),) * 3
    assert game.current_player == "X"
    assert game.winner is None
    assert game.winning_line is None
    assert game.is_draw is False
    assert game.is_over is False


def test_players_alternate():
    game = Game()
    game.place(0, 0)
    assert game.board[0][0] == "X"
    assert game.current_player == "O"
    game.place(1, 1)
    assert game.board[1][1] == "O"
    assert game.current_player == "X"


def test_board_snapshot_is_immutable_and_stable():
    game = Game()
    before = game.board
    assert isinstance(before, tuple)
    assert all(isinstance(row, tuple) for row in before)
    game.place(2, 2)
    assert before[2][2] is None
    assert game.board[2][2] == "X"


@pytest.mark.parametrize(
    "row, col",
    [(-1, 0), (0, -1), (3, 0), (0, 3), (1.0, 1), (1, "1"), (None, 0), (True, 0)],
)
def test_out_of_range_or_wrong_type_is_rejected(row, col):
    game = Game()
    with pytest.raises(InvalidMove):
        game.place(row, col)
    assert game.board == ((None, None, None),) * 3
    assert game.current_player == "X"


def test_taken_cell_is_rejected_and_turn_does_not_change():
    game = Game()
    game.place(0, 0)
    with pytest.raises(InvalidMove):
        game.place(0, 0)
    assert game.board[0][0] == "X"
    assert game.current_player == "O"


@pytest.mark.parametrize("index", [0, 1, 2])
def test_row_win(index):
    game = Game()
    other = (index + 1) % 3
    play(game, [(index, 0), (other, 0), (index, 1), (other, 1), (index, 2)])
    assert game.winner == "X"
    assert game.winning_line == ((index, 0), (index, 1), (index, 2))
    assert game.is_over is True
    assert game.is_draw is False


@pytest.mark.parametrize("index", [0, 1, 2])
def test_column_win(index):
    game = Game()
    other = (index + 1) % 3
    play(game, [(0, index), (0, other), (1, index), (1, other), (2, index)])
    assert game.winner == "X"
    assert game.winning_line == ((0, index), (1, index), (2, index))


def test_main_diagonal_win():
    game = Game()
    play(game, [(0, 0), (0, 1), (1, 1), (0, 2), (2, 2)])
    assert game.winner == "X"
    assert game.winning_line == ((0, 0), (1, 1), (2, 2))


def test_anti_diagonal_win():
    game = Game()
    play(game, [(0, 2), (0, 0), (1, 1), (0, 1), (2, 0)])
    assert game.winner == "X"
    assert game.winning_line == ((0, 2), (1, 1), (2, 0))


def test_o_can_win():
    game = Game()
    play(game, [(0, 0), (1, 0), (0, 1), (1, 1), (2, 2), (1, 2)])
    assert game.winner == "O"
    assert game.winning_line == ((1, 0), (1, 1), (1, 2))
    assert game.current_player == "O"


def test_draw():
    game = Game()
    play(
        game,
        [(0, 0), (0, 1), (0, 2), (1, 1), (1, 0), (1, 2), (2, 1), (2, 0), (2, 2)],
    )
    assert game.winner is None
    assert game.winning_line is None
    assert game.is_draw is True
    assert game.is_over is True


def test_win_on_the_last_cell_is_a_win_not_a_draw():
    game = Game()
    play(
        game,
        [(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 1), (2, 0), (2, 2)],
    )
    assert game.winner == "X"
    assert game.is_draw is False
    assert game.is_over is True


def test_no_moves_after_game_over():
    game = Game()
    play(game, [(0, 0), (1, 0), (0, 1), (1, 1), (0, 2)])
    snapshot = game.board
    with pytest.raises(InvalidMove):
        game.place(2, 2)
    assert game.board == snapshot
    assert game.winner == "X"


def test_reset_returns_to_a_fresh_game():
    game = Game()
    play(game, [(0, 0), (1, 0), (0, 1), (1, 1), (0, 2)])
    game.reset()
    assert game.board == ((None, None, None),) * 3
    assert game.current_player == "X"
    assert game.winner is None
    assert game.winning_line is None
    assert game.is_over is False
    game.place(1, 1)
    assert game.board[1][1] == "X"
